#!/usr/bin/env python3
"""Regenerate bảng Module index trong tasks/todo.md từ 20 todo-*.md.

Bảng có 5 cột:
  - # (số thứ tự test flow)
  - Module (title)
  - File (link)
  - Tasks (count + status icons)
  - Phase / Task IDs (group by phase, compress contiguous numeric)

Module ordering: theo test flow dep — pre-test → tier 0/1 (qtht/actor)
→ tier 2 entry → workflow E2E → output → cross-cutting.

Idempotent: chạy lại sau khi flip task ở module file.

Usage:
  python3 tools/build-master-index.py            # preview stdout
  python3 tools/build-master-index.py --write    # ghi vào todo.md
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TASKS_DIR = ROOT / "tasks"
MASTER = TASKS_DIR / "todo.md"

START_MARKER = "<!-- BEGIN: module-index (auto-generated by tools/build-master-index.py) -->"
END_MARKER = "<!-- END: module-index -->"

# Module ordering theo test flow dep:
# 1-2: pre-test + qtht (foundation: deploy + DM + account)
# 3-6: tier 1 actor (TC TV → DN → TVV/CG → NHT)
# 7-13: tier 2 entry + workflow (HD/VV/TVCS → HĐ TV/Đào tạo/BM/Kho QA → Đánh giá)
# 14-17: workflow output (Chi trả / TVN / CT)
# 18-20: verification (Dashboard / Báo cáo / Cross-cutting)
MODULE_ORDER = [
    "pre-test", "qtht",
    "tc-tv", "doanh-nghiep", "tvv-cg", "nht",
    "hoi-dap", "vu-viec", "tvcs",
    "hop-dong-tv", "dao-tao", "bieu-mau", "kho-qa", "danh-gia-hq",
    "chi-tra", "tv-nhanh", "ct-htpldn",
    "dashboard", "bao-cao", "cross-cutting",
]

MODULE_TITLES = {
    "pre-test": "Pre-test",
    "qtht": "QTHT — Quản trị hệ thống",
    "tc-tv": "TC TV — Tổ chức tư vấn",
    "doanh-nghiep": "Doanh nghiệp",
    "tvv-cg": "TVV + CG",
    "nht": "NHT — Người hỗ trợ",
    "hoi-dap": "Hỏi đáp",
    "vu-viec": "Vụ việc",
    "tvcs": "TVCS — Tư vấn chuyên sâu",
    "hop-dong-tv": "HĐ TV — Hợp đồng tư vấn",
    "dao-tao": "Đào tạo (KH năm / CTĐT / Khóa / NHCH / ĐKT / GV / HV / LH)",
    "bieu-mau": "Biểu mẫu",
    "kho-qa": "Kho QA",
    "danh-gia-hq": "Đánh giá Hiệu quả HTPL",
    "chi-tra": "Chi trả",
    "tv-nhanh": "TV nhanh",
    "ct-htpldn": "CT HTPLDN",
    "dashboard": "Dashboard",
    "bao-cao": "Báo cáo",
    "cross-cutting": "Cross-cutting (SLA / API / Permission / Profile)",
}

ICON_RE = r'(?:✅|⚠️|🚫|⏳|🟢|❌|🔵)'
TASK_HEADER = re.compile(
    rf'^- ({ICON_RE})(?:\s*<a id="[^"]+"></a>)?\s*\*\*(R7\.[A-Za-z0-9.\-]+)\*\*'
)
ICONS_DISPLAY_ORDER = ["✅", "🟢", "🔵", "⚠️", "🚫", "⏳", "❌"]
PHASE_ORDER = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "E"]


def task_id_to_phase(tid: str) -> str:
    parts = tid.split(".")
    if len(parts) < 2:
        return "?"
    seg = parts[1]
    if seg.startswith("E"):
        return "E"
    return seg[0]


def task_sort_key(tid: str):
    tokens = re.split(r'[.\-]', tid)
    key = []
    for t in tokens:
        if t.isdigit():
            key.append((0, int(t)))
        else:
            m = re.match(r'^([A-Za-z]+)(\d*)(.*)$', t)
            if m:
                a, n, r = m.groups()
                key.append((1, a, int(n) if n else -1, r))
            else:
                key.append((1, t, -1, ""))
    return key


def compress_phase_with_icons(tasks: list[tuple[str, str]]) -> str:
    """Compress (icon, task_id) list. Mỗi task hiện icon trạng thái real-time.

    Strategy:
      1. Sort theo task_sort_key (tid).
      2. Nếu TẤT CẢ task cùng 1 icon AND IDs là R7.<X>.<Y> numeric liên tiếp
         (≥3 task) → compress thành "<icon>R7.<X>.<a>..<b>".
      3. Else: liệt kê từng task có icon prefix, ngăn cách bằng ", ".
    """
    if not tasks:
        return ""
    tasks_sorted = sorted(tasks, key=lambda t: task_sort_key(t[1]))

    # Try compress: tất cả cùng icon + numeric Y liên tiếp
    unique_icons = {t[0] for t in tasks_sorted}
    if len(unique_icons) == 1 and len(tasks_sorted) >= 3:
        common_icon = next(iter(unique_icons))
        pure_num = re.compile(r'^R7\.(\d+)\.(\d+)$')
        nums: list[int] | None = []
        common_x: str | None = None
        for _, tid in tasks_sorted:
            m = pure_num.match(tid)
            if not m:
                nums = None
                break
            x, y = m.group(1), int(m.group(2))
            if common_x is None:
                common_x = x
            elif x != common_x:
                nums = None
                break
            nums.append(y)
        if nums and nums == list(range(nums[0], nums[-1] + 1)):
            return f"{common_icon}R7.{common_x}.{nums[0]}..{nums[-1]}"

    return ", ".join(f"{icon}{tid}" for icon, tid in tasks_sorted)


def render_phase_cell(by_phase: dict[str, list[tuple[str, str]]]) -> str:
    parts = []
    for p in PHASE_ORDER:
        if p in by_phase:
            label = "Trụ E" if p == "E" else f"P{p}"
            parts.append(f"**{label}** {compress_phase_with_icons(by_phase[p])}")
    return "<br>".join(parts)


def render_status(icons: list[str]) -> str:
    counter = Counter(icons)
    parts = [f"{ic}{counter[ic]}" for ic in ICONS_DISPLAY_ORDER if counter.get(ic, 0) > 0]
    return " ".join(parts)


def parse_module(path: Path):
    by_phase: dict[str, list[tuple[str, str]]] = defaultdict(list)
    icons: list[str] = []
    for line in path.read_text(encoding="utf-8").split("\n"):
        m = TASK_HEADER.match(line)
        if not m:
            continue
        icon, tid = m.group(1), m.group(2)
        icons.append(icon)
        by_phase[task_id_to_phase(tid)].append((icon, tid))
    return by_phase, icons


def build_section() -> str:
    lines = [
        "## Module index — sắp xếp theo thứ tự test full luồng",
        "",
        "> Module ordering theo dep flow: foundation (pre-test + qtht) → tier 1 actor → tier 2 entry + workflow → output → verification.  ",
        "> Cột **Phase / Task IDs** group task theo Phase (P0..P8 + Trụ E). Click file để xem Kết quả/Bug/Cần có sẵn chi tiết.  ",
        "> Bảng auto-gen từ `tools/build-master-index.py` — sửa task ở module file → chạy lại `python3 tools/build-master-index.py --write`.",
        "",
        "| # | Module | File | Tasks | Status | Phase / Task IDs |",
        "|:-:|---|---|:-:|---|---|",
    ]
    total_tasks = 0
    for idx, slug in enumerate(MODULE_ORDER, 1):
        path = TASKS_DIR / f"todo-{slug}.md"
        if not path.exists():
            lines.append(f"| {idx} | {MODULE_TITLES.get(slug, slug)} | _missing_ | — | — | — |")
            continue
        by_phase, icons = parse_module(path)
        total_tasks += len(icons)
        title = MODULE_TITLES.get(slug, slug)
        link = f"[todo-{slug}.md](todo-{slug}.md)"
        lines.append(
            f"| {idx} | {title} | {link} | {len(icons)} | {render_status(icons)} | {render_phase_cell(by_phase)} |"
        )
    lines.append("")
    lines.append(f"**Tổng:** {total_tasks} task / {len(MODULE_ORDER)} module.")
    lines.append("")
    return "\n".join(lines)


def write_master(section: str) -> None:
    if not MASTER.exists():
        print(f"ERROR: {MASTER} not found", file=sys.stderr)
        sys.exit(1)
    content = MASTER.read_text(encoding="utf-8")

    # Step 1: Strip stale "## Task list theo Phase" block (từ phiên bản trước)
    stale_start = "<!-- BEGIN: task-by-phase"
    stale_end = "<!-- END: task-by-phase -->"
    if stale_start in content and stale_end in content:
        pat = re.compile(
            re.escape(stale_start) + r".*?" + re.escape(stale_end) + r"\n*(?:---\n+)?",
            re.DOTALL,
        )
        content = pat.sub("", content)

    # Step 2: Replace block giữa current BEGIN/END marker, hoặc replace section "## Module index..."
    block = f"{START_MARKER}\n{section}{END_MARKER}\n"

    if START_MARKER in content and END_MARKER in content:
        pat = re.compile(
            re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER) + r"\n?",
            re.DOTALL,
        )
        content = pat.sub(block, content)
    else:
        # Replace existing "## Module index ..." section (giữ phần khác nguyên).
        # Section bao gồm heading + bảng + footnote tới khi gặp section khác (## ... hoặc --- + ##).
        old_pat = re.compile(
            r"^## Module index[^\n]*\n.*?(?=^## |\Z)",
            re.MULTILINE | re.DOTALL,
        )
        if old_pat.search(content):
            content = old_pat.sub(block + "\n", content, count=1)
        else:
            # Insert trước section "## Shared file"
            anchor = "## Shared file"
            if anchor in content:
                content = content.replace(anchor, block + "\n" + anchor)
            else:
                content = content.rstrip() + "\n\n" + block

    # Cleanup: collapse 3+ blank lines → 2
    content = re.sub(r"\n{4,}", "\n\n\n", content)
    MASTER.write_text(content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Ghi vào todo.md (else print stdout)")
    args = parser.parse_args()

    section = build_section()
    if args.write:
        write_master(section)
        print(f"✅ Wrote {len(MODULE_ORDER)} module rows → {MASTER.relative_to(ROOT)}", file=sys.stderr)
    else:
        sys.stdout.write(section)


if __name__ == "__main__":
    main()
