#!/usr/bin/env python3
"""Insert/update bảng "Tổng hợp module" vào mỗi todo-{slug}.md.

Bảng hiển thị task count theo Phase × icon, kèm Task IDs có icon prefix.
Idempotent: chạy lại sau khi flip task ở module file.

Usage:
  python3 tools/build-module-summaries.py            # preview stdout (1 file/section)
  python3 tools/build-module-summaries.py --write    # ghi vào tất cả 20 file
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TASKS_DIR = ROOT / "tasks"

START_MARKER = "<!-- BEGIN: module-summary (auto-generated by tools/build-module-summaries.py) -->"
END_MARKER = "<!-- END: module-summary -->"

MODULE_SLUGS = [
    "pre-test", "qtht",
    "tc-tv", "doanh-nghiep", "tvv-cg", "nht",
    "hoi-dap", "vu-viec", "tvcs",
    "hop-dong-tv", "dao-tao", "bieu-mau", "kho-qa", "danh-gia-hq",
    "chi-tra", "tv-nhanh", "ct-htpldn",
    "dashboard", "bao-cao", "cross-cutting",
]

ICON_RE = r'(?:✅|⚠️|🚫|⏳|🟢|❌|🔵)'
TASK_HEADER = re.compile(
    rf'^- ({ICON_RE})(?:\s*<a id="[^"]+"></a>)?\s*\*\*(R7\.[A-Za-z0-9.\-]+)\*\*'
)
ICON_COLS = ["🟢", "🔵", "✅", "⚠️", "🚫", "⏳", "❌"]
PHASE_ORDER = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "E"]


def task_id_to_phase(tid: str) -> str:
    parts = tid.split(".")
    if len(parts) < 2:
        return "?"
    seg = parts[1]
    if seg.startswith("E"):
        return "E"
    return seg[0]


def phase_label(p: str) -> str:
    return "Trụ E" if p == "E" else f"P{p}"


def task_sort_key(tid: str):
    tokens = re.split(r'[.\-]', tid)
    key = []
    for t in tokens:
        if t.isdigit():
            key.append((0, int(t)))
        else:
            m = re.match(r'^([A-Za-z]+)(\d*)(.*)$', t)
            if m:
                a, n, r = m.groups()
                key.append((1, a, int(n) if n else -1, r))
            else:
                key.append((1, t, -1, ""))
    return key


def parse_module(path: Path):
    by_phase: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for line in path.read_text(encoding="utf-8").split("\n"):
        m = TASK_HEADER.match(line)
        if not m:
            continue
        icon, tid = m.group(1), m.group(2)
        by_phase[task_id_to_phase(tid)].append((icon, tid))
    return by_phase


def task_anchor(tid: str) -> str:
    """Convert task ID to its <a id="..."></a> anchor format.

    Pattern verified across 20 module file: lowercase + dot→hyphen.
    Examples: R7.3.1 → r7-3-1, R7.4.A3-PUBLIC → r7-4-a3-public, R7.3.1.MoB → r7-3-1-mob.
    """
    return tid.lower().replace(".", "-")


def render_table(by_phase: dict[str, list[tuple[str, str]]]) -> str:
    if not by_phase:
        return "_(no task)_\n"
    header = "| Phase | Tổng | " + " | ".join(ICON_COLS) + " | Task IDs |"
    sep = "|---|:-:|" + "|".join([":-:"] * len(ICON_COLS)) + "|---|"
    rows = [header, sep]

    grand_total = 0
    grand_counter: Counter[str] = Counter()

    for p in PHASE_ORDER:
        if p not in by_phase:
            continue
        tasks = sorted(by_phase[p], key=lambda t: task_sort_key(t[1]))
        cnt = Counter(icon for icon, _ in tasks)
        total = len(tasks)
        grand_total += total
        for ic in ICON_COLS:
            grand_counter[ic] += cnt.get(ic, 0)
        ids = " · ".join(f"{icon}[{tid}](#{task_anchor(tid)})" for icon, tid in tasks)
        cells = [f"**{phase_label(p)}**", str(total)]
        cells += [str(cnt.get(ic, 0)) for ic in ICON_COLS]
        cells.append(ids)
        rows.append("| " + " | ".join(cells) + " |")

    total_cells = ["**Tổng**", f"**{grand_total}**"]
    total_cells += [f"**{grand_counter[ic]}**" for ic in ICON_COLS]
    total_cells.append("")
    rows.append("| " + " | ".join(total_cells) + " |")

    return "\n".join(rows) + "\n"


def build_section(by_phase) -> str:
    lines = [
        "## Tổng hợp module",
        "",
        "> Bảng auto-gen từ `tools/build-module-summaries.py` — sửa task → chạy lại `python3 tools/build-module-summaries.py --write`.",
        "",
        render_table(by_phase).rstrip(),
        "",
    ]
    return "\n".join(lines)


def update_file(path: Path, write: bool) -> str:
    by_phase = parse_module(path)
    section = build_section(by_phase)
    block = f"{START_MARKER}\n{section}{END_MARKER}\n"

    content = path.read_text(encoding="utf-8")

    if START_MARKER in content and END_MARKER in content:
        pat = re.compile(
            re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER) + r"\n?",
            re.DOTALL,
        )
        new_content = pat.sub(block, content)
    else:
        # Insert trước "## Tasks" heading
        anchor = re.compile(r"^## Tasks\b", re.MULTILINE)
        m = anchor.search(content)
        if not m:
            raise RuntimeError(f"{path.name}: không tìm thấy heading '## Tasks'")
        idx = m.start()
        new_content = content[:idx] + block + "\n" + content[idx:]

    # Cleanup: collapse 3+ blank lines → 2
    new_content = re.sub(r"\n{4,}", "\n\n\n", new_content)

    if write and new_content != content:
        path.write_text(new_content, encoding="utf-8")
    return block


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Ghi vào todo-*.md (else preview file đầu)")
    args = parser.parse_args()

    if not args.write:
        # Preview: show section của file đầu tiên có task
        for slug in MODULE_SLUGS:
            path = TASKS_DIR / f"todo-{slug}.md"
            if not path.exists():
                continue
            by_phase = parse_module(path)
            print(f"=== Preview: todo-{slug}.md ===\n")
            print(build_section(by_phase))
            return

    written = 0
    skipped = 0
    for slug in MODULE_SLUGS:
        path = TASKS_DIR / f"todo-{slug}.md"
        if not path.exists():
            print(f"⚠️  todo-{slug}.md missing, skip", file=sys.stderr)
            skipped += 1
            continue
        try:
            update_file(path, write=True)
            written += 1
        except Exception as e:
            print(f"❌ {path.name}: {e}", file=sys.stderr)
            skipped += 1
    print(f"✅ Updated {written} file(s) · skipped {skipped}", file=sys.stderr)


if __name__ == "__main__":
    main()
